export interface Project {
  project: string;
  shortDescription: string;
  description: string;
  repo: Array<{ web: string; iOS?: string }>;
  link: string;
  images: Array<{ web: string; mobile: string; iOS?: string }>;
  stack: string[];
  keywords: string[];
  role: string;
  complexity: string;
  architecture: string;
  performance: string[];
  testing: string[];
  deployment: string[];
  collaboration: string;
  impact: string;
  seniority: string;
  scalability: string;
  maintainability: string;
  experimental?: boolean;
  aiPowered?: boolean;
  crossPlatform?: boolean;
  mobileExpertise?: boolean;
}

// Canonical slug for each project's /work/[slug] page
export const projectSlugs: Record<string, string> = {
  'POKÉ COLLECTOR': 'poke-collector',
  'Protein Quality Calculator': 'protein-checker',
  'FORK IN THE ROAD': 'fork-in-the-road',
};

export const projects: Project[] = [
  {
    project: 'POKÉ COLLECTOR',
    shortDescription:
      'Modern Pokemon TCG collection app built with Next.js 15. Search the complete card database with advanced filtering, create personal collections, and manage favorites. Features user authentication, responsive design, and real-time search across energy types, subtypes, and sets.',
    description:
      'A comprehensive Pokemon Trading Card Game collection management platform showcasing advanced frontend architecture and user experience design. Built with Next.js 15 App Router, the application demonstrates sophisticated state management, real-time search capabilities, and seamless integration with external APIs. Features include multi-criteria filtering with complex query building, pagination handling for large datasets, responsive design with mobile-first approach, and secure user authentication with collection persistence. The app integrates with the Pokemon TCG API for real-time card data, implements MongoDB for user collection storage, and utilizes Clerk for authentication. Advanced features include advanced search with energy type filtering, subtype categorization, set browsing, and comprehensive card detail views with image optimization.',
    repo: [{ web: 'https://github.com/akpersad/TCG-Demo' }],
    link: 'https://poke-collector-tan.vercel.app/',
    images: [
      {
        web: '/projects/poke-collector-web.png',
        mobile: '/projects/poke-collector-mobile.png',
      },
    ],
    stack: [
      'Next.js 15',
      'React 19',
      'TypeScript',
      'Tailwind CSS 4',
      'SCSS Modules',
      'MongoDB',
      'Clerk Authentication',
      'Pokemon TCG API',
      'Axios',
      'React Hot Toast',
      'Turbopack',
      'ESLint',
      'PostCSS',
    ],
    keywords: [
      'Next.js',
      'React',
      'TypeScript',
      'Frontend Development',
      'Full-Stack Development',
      'API Integration',
      'Database Design',
      'User Authentication',
      'Responsive Design',
      'Mobile-First Design',
      'State Management',
      'Component Architecture',
      'Performance Optimization',
      'Image Optimization',
      'Search Functionality',
      'Data Filtering',
      'Pagination',
      'MongoDB',
      'REST API',
      'Modern JavaScript',
      'ES6+',
      'CSS-in-JS',
      'Tailwind CSS',
      'SCSS',
      'Web Development',
      'Frontend Architecture',
      'User Experience',
      'UI/UX Design',
      'Progressive Web App',
      'Client-Side Rendering',
      'Server-Side Rendering',
    ],
    // Hidden ATS fields (not displayed in UI)
    role: 'Senior Frontend Developer',
    complexity: 'Advanced',
    architecture: 'Component-Based',
    performance: [
      'Image Optimization',
      'Lazy Loading',
      'Code Splitting',
      'API Caching',
    ],
    testing: ['Unit Testing', 'Integration Testing'],
    deployment: ['Vercel', 'CI/CD'],
    collaboration: 'Solo Project',
    impact: 'Production Ready',
    seniority: 'Senior Level',
    scalability: 'High',
    maintainability: 'Excellent',
  },
  {
    project: 'Protein Quality Calculator',
    shortDescription:
      'Cross-platform protein quality calculator with web and iOS versions. Calculate quality-adjusted protein using scientific DIAAS/PDCAAS scores. Features 50+ protein sources, multi-source calculations, history tracking, and educational content across platforms.',
    description:
      'A sophisticated cross-platform nutrition calculation platform demonstrating advanced frontend engineering and mobile development expertise. The web version, built with Next.js 15 and TypeScript, showcases expert-level state management using React Context API, custom hooks for data persistence, and advanced form handling with validation. The native iOS version, built with Swift 5.0 and SwiftUI, demonstrates modern iOS architecture patterns including MVVM, Core Data integration, and native iOS design patterns. Both platforms feature multi-source protein calculations with percentage weighting, scientific DIAAS/PDCAAS score integration, comprehensive protein database with 50+ sources, calculation history with persistent storage, and educational content delivery. The project demonstrates advanced TypeScript usage with strict typing, custom utility functions for mathematical calculations, responsive design with Tailwind CSS 4, modern React patterns including custom hooks and context providers, and cross-platform development with shared business logic. Advanced features include data export/import functionality, calculation statistics, haptic feedback integration (iOS), and comprehensive error handling with platform-specific user feedback.',
    repo: [
      {
        web: 'https://github.com/akpersad/ProteinCheckerWeb',
        iOS: 'https://github.com/akpersad/ProteinCheckerSwift',
      },
    ],
    link: 'https://protein-checker-web.vercel.app/',
    images: [
      {
        web: '/projects/protein-checker-web.png',
        mobile: '/projects/protein-checker-mobile.png',
        iOS: '/projects/protein-checker-ios.png',
      },
    ],
    stack: [
      'Next.js 15',
      'React 19',
      'TypeScript',
      'Tailwind CSS 4',
      'Headless UI',
      'Heroicons',
      'React Context API',
      'Custom Hooks',
      'Local Storage',
      'UUID',
      'Swift 5.0',
      'SwiftUI',
      'iOS 17+',
      'Core Data',
      'UserDefaults',
      'JSON Encoding/Decoding',
      'Combine Framework',
      'Async/Await',
      'MVVM Architecture',
      'Protocol-Oriented Programming',
      'Generics',
      'Turbopack',
      'ESLint',
      'Husky',
      'PostCSS',
      'Xcode',
    ],
    keywords: [
      'Next.js',
      'React',
      'TypeScript',
      'Frontend Development',
      'Advanced TypeScript',
      'State Management',
      'React Context',
      'Custom Hooks',
      'Form Handling',
      'Data Validation',
      'Mathematical Calculations',
      'Scientific Computing',
      'Data Persistence',
      'Local Storage',
      'Responsive Design',
      'Tailwind CSS',
      'Headless UI',
      'Component Design',
      'User Interface',
      'User Experience',
      'Data Visualization',
      'Performance Optimization',
      'Modern React Patterns',
      'Frontend Architecture',
      'Web Development',
      'JavaScript',
      'ES6+',
      'CSS-in-JS',
      'Progressive Web App',
      'Client-Side Application',
      'Data Management',
      'Error Handling',
      'User Feedback',
      'Accessibility',
      'Cross-Browser Compatibility',
      'iOS Development',
      'Swift',
      'SwiftUI',
      'Mobile Development',
      'Native iOS',
      'iOS Architecture',
      'MVVM Pattern',
      'Core Data',
      'JSON Handling',
      'Protocol-Oriented Programming',
      'Generics',
      'Async/Await',
      'Combine Framework',
      'Swift Concurrency',
      'iOS Design Patterns',
      'Mobile UX',
      'Adaptive Layouts',
      'Navigation Patterns',
      'Haptic Feedback',
      'Cross-Platform Development',
      'Mobile Architecture',
      'iOS Performance',
      'Memory Management',
      'ARC',
      'iOS Testing',
      'Xcode',
      'iOS Simulator',
      'App Store Guidelines',
      'iOS Human Interface Guidelines',
    ],
    // Hidden ATS fields (not displayed in UI)
    role: 'Lead Frontend Developer',
    complexity: 'Expert',
    architecture: 'Cross-Platform',
    performance: [
      'Data Persistence',
      'Local Storage',
      'Memory Management',
      'iOS Performance',
    ],
    testing: ['Unit Testing', 'Integration Testing', 'iOS Testing'],
    deployment: ['Vercel', 'App Store', 'CI/CD'],
    collaboration: 'Solo Project',
    impact: 'Production Ready',
    seniority: 'Lead Level',
    scalability: 'High',
    maintainability: 'Excellent',
    crossPlatform: true,
    mobileExpertise: true,
  },
  {
    project: 'FORK IN THE ROAD',
    shortDescription:
      'Mobile-first PWA that ends the "where should we eat?" group chat debate. Start a Fork (a lightweight decision with candidate restaurants, a mode, and a timer), drop one link in the chat, and everyone votes with just a display name, no account required. Weighted spin or ranked voting, live results over Server-Sent Events, and crews that remember shared decision history.',
    description:
      'A full-stack group decision platform built with Next.js 16 App Router and React 19, rebuilt from the ground up as a v2 re-imagination that cut a ~113k-line v1 down to ~20k lines while keeping the proven decision math. The core object is the Fork: a few candidate spots, a decision mode, and a timer, shared as one link where anyone can vote with just a display name. Guest identity is a signed httpOnly cookie (HMAC-SHA256) holding zero PII, with a one-way idempotent "claim your votes" upgrade to a full Clerk account. The unauthenticated write surface is hardened with signed per-fork vote tokens verified before any database read, layered per-IP and per-fork rate limits, ballot caps, and expiry enforcement on every write. The decision engine is a pure module with injected history, clock, and RNG: weighted random selection with 30-day decay and a 10% floor, plus ranked-choice voting scored 3/2/1 with deterministic tie-breaks, all pinned by unit tests. Fork rooms update live over Server-Sent Events with no websocket infrastructure, and deadlines are enforced lazily on every read with no cron: closes seal the fork first, then compute consensus from the sealed document, so racing closers can never disagree. Google Places sits behind a default-closed billing gate with a 30-day cache, so dev, CI, and tests can never bill. Crews emerge from behavior: after the same accounts finish three forks together, the app suggests a crew and back-attaches the shared history so weight decay works from day one. The "Tonight\'s board" design system (departure-board identity, OKLCH design tokens, a rationed gold accent, and a split-flap winner reveal that respects reduced motion) ships with the app at /gallery, with every palette pair WCAG-verified numerically. Quality gates in CI: Jest with ratchet-only coverage thresholds, real multi-user Playwright journeys (guest voting from raw links in incognito contexts, a three-user vote converging over SSE, the claim flow), axe WCAG 2.x AA scans in both light and dark modes, and Lighthouse performance floors.',
    repo: [{ web: 'https://github.com/akpersad/YouHungry' }],
    link: 'https://www.forkintheroad.app',
    images: [
      {
        web: '/projects/fork-in-the-road-web.png',
        mobile: '/projects/fork-in-the-road-mobile.png',
      },
    ],
    stack: [
      'Next.js 16',
      'React 19',
      'TypeScript 6',
      'Tailwind CSS 4',
      'OKLCH Design Tokens',
      'MongoDB',
      'Clerk Authentication',
      'Zod',
      'Server-Sent Events (SSE)',
      'Google Places API',
      'Resend (Email)',
      'Web Push (VAPID)',
      'Svix (Webhooks)',
      'Vercel Analytics',
      'Vercel Speed Insights',
      'Jest',
      'Playwright',
      'Lighthouse CI',
      'axe-core',
      'Turbopack',
      'ESLint',
      'Prettier',
      'Husky',
      'lint-staged',
    ],
    keywords: [
      'Next.js',
      'React',
      'React Server Components',
      'TypeScript',
      'Full-Stack Development',
      'MongoDB',
      'REST API',
      'Server-Sent Events',
      'Real-Time Updates',
      'Google Places API',
      'Authentication',
      'Clerk',
      'Guest Access',
      'HMAC Signing',
      'Token-Based Security',
      'Rate Limiting',
      'Zod',
      'Schema Validation',
      'PWA',
      'Progressive Web App',
      'Service Worker',
      'Push Notifications',
      'Email Notifications',
      'Resend',
      'Ranked-Choice Voting',
      'Weighted Random Selection',
      'Algorithm Design',
      'Group Decision Making',
      'Consensus Algorithms',
      'Concurrency Control',
      'Idempotency',
      'Data Migration',
      'Legacy Modernization',
      'Design Systems',
      'Design Tokens',
      'OKLCH Color',
      'Dark Mode',
      'Reduced Motion',
      'Accessibility',
      'WCAG',
      'axe-core',
      'Lighthouse',
      'Performance Optimization',
      'Caching Strategy',
      'Cost Optimization',
      'E2E Testing',
      'Playwright',
      'Unit Testing',
      'Jest',
      'Test Coverage',
      'SEO',
      'Vercel',
      'CI/CD',
      'GitHub Actions',
      'Webhooks',
      'Responsive Design',
      'Mobile-First Design',
      'Tailwind CSS',
      'Component Architecture',
      'API Integration',
    ],
    // Hidden ATS fields (not displayed in UI)
    role: 'Lead Full-Stack Developer',
    complexity: 'Expert',
    architecture: 'Full-Stack with API + Services',
    performance: [
      'Live Updates via SSE',
      'No-Account Guest Voting',
      'Weighted Spin Algorithm',
      'Ranked-Choice Voting',
      '30-Day Places Cache',
      'Default-Closed Billing Gate',
    ],
    testing: [
      'Unit Testing (Jest)',
      'Multi-User E2E Testing (Playwright)',
      'Accessibility (axe-core, Light + Dark)',
      'Lighthouse CI',
    ],
    deployment: ['Vercel', 'GitHub Actions', 'CI/CD'],
    collaboration: 'Solo Project',
    impact: 'Production Ready',
    seniority: 'Lead Level',
    scalability: 'High',
    maintainability: 'Excellent',
  },
];
